### ISSUE TITLE
404 when connecting to localhost (docker)

### ISSUE THREAD

**Issue by MikeS-nth** [pgonzaleznetwork/sfdc-happy-soup#156] opened 2021-08-16 17:52 UTC
Hello,

I am trying to run Happy Soup locally using Docker via [these instructions](https://www.youtube.com/watch?v=WQhz91JSl3o).

`npm run dc-build` seems to run successfully; however, when I try to connect via http://localhost:3000, I get the following error:

`{
  "error": true,
  "statusCode": 404,
  "message": "Not Found",
  "stack": "NotFoundError: Not Found\n    at /app/backend/server/app.js:45:8\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/backend/server/app.js:25:5\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7"
}`

Here is my `docker-compose.yml` (keys redacted)

```
version: '3'

services:
  redis:
    image: 'redis'
  webapp:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OAUTH_CLIENT_ID=#KEY
      - OAUTH_CLIENT_SECRET=#KEY
      - SFDC_API_VERSION=49.0
      - SESSION_SECRET=whatever
      - PORT=3000
      - CORS_DOMAINS=http://localhost:3000,https://sfdc-happy-soup.herokuapp.com,https://happysoup.io
      - ENFORCE_SSL=false
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OAUTH_CLIENT_ID=#KEY
      - OAUTH_CLIENT_SECRET=#KEY
      - SFDC_API_VERSION=49.0
      - SESSION_SECRET=whatever
      - PORT=3000
      - CORS_DOMAINS=http://localhost:3000,https://sfdc-happy-soup.herokuapp.com,https://happysoup.io
      - ENFORCE_SSL=false
```

Any assistance is greatly appreciated!!

**Comment by pgonzaleznetwork** [comment] 2021-08-16 22:14
Hi there,

I think something may have changed since this is a new version of the app.
I'll try to reproduce the issue and get back to you. Can you share a
screenshot nod the error? Is it in the UI?

**Comment by MikeS-nth** [comment] 2021-08-16 23:44
Sure.  Here are two screenshots:  1) console output from when `npm run dc-build` finishes to when the error occurs; 2) error message in the browser.  The error is not in the UI; it occurs before getting to the UI after launching the application.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/7927110/129642375-f9cb4d4f-31e7-4b8e-adf8-d3e3f66affd9.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/7927110/129642436-f91d15af-2dbf-4be6-aa92-6f2f71ec9e33.png">

**Comment by pgonzaleznetwork** [comment] 2021-08-17 09:29
@MikeS-nth Thank you very much for reporting this. I've fixed this now.

Please delete your local repository and clone it again, and follow the steps from there. Let me know how it goes

**Comment by MikeS-nth** [comment] 2021-08-17 13:40
Thanks very much for responding so quickly!  I deleted the directory, re-cloned from Github, and tried again.  Unfortunately, it is now throwing a different error.  I've attached the console output.  (It looks like the log file was not actually written to ~/.npm/_logs/)
[happy_soup_errors_17Aug2021.txt](https://github.com/pgonzaleznetwork/sfdc-happy-soup/files/7000381/happy_soup_errors_17Aug2021.txt)

**Comment by pgonzaleznetwork** [comment] 2021-08-17 14:58
Can you please join the slack channel so we can talk more real-time? https://join.slack.com/t/happysoupio/shared_invite/zt-oo8d5a1t-A04m7wkK16vwdd5oWtpbZg

**Comment by pgonzaleznetwork** [comment] 2021-08-17 16:48
Fixed by removing unnecessary lines from the docker file. Enjoy the app!

**Closed by pgonzaleznetwork** 2021-08-17 16:48 UTC
